<!-- Imports functions -->
<?php require_once  "includes/functions.php" ?>
<!-- Creates connection -->
<?php require_once "includes/connection.php" ?>
<!-- Creates DOM -->
<?php require_once "includes/header.php" ?>
<?php require_once "includes/nav.php" ?>
<?php require_once "includes/content.php" ?>
<?php require_once "includes/footer.php" ?>
